### ISSUE TITLE
Feature test coverage

### ISSUE THREAD

**Issue by drewburlingame** [bilal-fazlani/commanddotnet#107]
I've been working on increasing coverage of the CommandDotNet features.  

Below is a list of the feature areas I'm testing and the ones completed.
There is now some duplicated testing between these feature tests and some of the previous version.  I'll take a pass at cleaning those up over the next couple of weeks. 

- [x] Arguments
  - [x] Mapping args to types (exec, basic & detailed help)
    - [x] .net Types
      - [x] bool
      - [x] string
      - [x] struct (int)
      - [x] struct? (int)
      - [x] enum
      - [x] object (url)
      - [x] List< bool >
      - [x] List< string >
      - [x] List< struct >
      - [x] List< enum >
      - [x] List< object >
      - [x] Optional & Default value
	- [x] Lists
	  - [x] single operand list
	  - [x] multiple option lists
  - [x] Defining w/ Method Params (exec, basic & detailed help)
    - [x] ArgType
      - [x] Operand
      - [x] Option
  - [x] Defining w/ Argument Model (exec, basic & detailed help)
    - [x] ArgType
      - [x] Operand
      - [x] Option
    - [x] nested models
    - [x] ctor options
  - [x] General use
    - [x] Operand  (exec, basic & detailed help)
      - [x] order enforced
      - [x] included in example usage
	  - [ ] Requiredness	(not currently possible if defined as method param)
    - [x] Options
      - [x] flag clubbing
	  - [x] flags don't declare <BOOLEAN> type in help
	  - [x] flags don't declare allowed values 
    - [x] BooleanMode.Explicit
      - [x] displays allowed values
	- [x] mix options & operands in method
	  - [x] mix arg model & params in method
	  - [x] option lists can exist with argument lists
  - [x] AppSettings (exec, basic & detailed help)
    - [x] arg details
    - [x] arg mode
    - [x] bool mode
  - [x] Ctor options (exec, basic & detailed help)
    - [x] inherited / not inherited
  - [x] Fluent Validation (exec)
    - [x] skip help since it's not integrated
    - [x] complex scenarios not required
  - [ ] Arg Separator '--'
- [] Commands (exec, basic & detailed help)
  - [x] command
  - [] nested commands
    - [x] ctor options (not inherited)
    - [x] nested command via SubCommand attributed property
    - [x] nested command via SubCommand attributed nested class
  - [x] default methods
  - [x] default method w/ ctor
- [x] Help full coverage
  - [x] all attribute values included
    - [x] description
    - [x] short name, long name
    - [x] boolean mode
    - [x] BooleanMode.Explicit displays allowed values
    - [x] ApplicationMetadata
      - [x] Name displays in help
      - [x] Name overrides usage example
      - [x] Description
      - [x] ExtendedHelpText
  - [x] arguments, options & commands section
  - [x] example usage
  - [ ] Custom HelpProvider can be registered
- [x] AppSettings
  - [x] case
  - [x] version option
- [x] TypeDescriptor
  - [x] TypeConverter
  - [x] custom descriptor
- [x] DependencyInjection
  - [x] can be registered (tested as a part of the framework)
  - [x] injects into nested commands (tested as a part of the framework)
- [x] CustomInterceptor
  - [x] can be registered
- [x] Misc
  - [x] custom return codes
  - [x] Async methods
  - [x] Exception handling
    - [ ] AppSettings.ThrowOnUnexpectedArgument 

Need to determine the best way to test these
- [x] Prompting
- [ ] AnsiConsole (does this get used?  it seems there are other libraries that serve this purpose)
- [x] PipedInput

**Comment by drewburlingame** [comment]
I've marked a few tests as skipped because of known bugs or 'not-implemented' as a reminder for me to add issues for them.

**Comment by drewburlingame** [comment]
This is my first time really using xunit.  I'm glad I finally got the opportunity so I could understand how it works.  NUnit has better support for 'Theory' or Data Driven testing.  NUnit's TestCaseData makes it easy to skip and categories scenarios from the data sources.  If we switched to that, the scenario framework and output will be a bit cleaner.

**Comment by drewburlingame** [comment]
There's a readme @ https://github.com/bilal-fazlani/commanddotnet/tree/master/CommandDotNet.Tests/FeatureTests for instructions and examples for writing tests

**Comment by drewburlingame** [comment]
Current coverage: 85%.  
If we exclude AnsiConsole & PipedInput, it's 90%

![image](https://user-images.githubusercontent.com/103345/59411560-769a5900-8db3-11e9-9ee1-9ea560a601f9.png)

**Comment by bilal-fazlani** [comment]
This is awesome 🎉

**Comment by drewburlingame** [comment]
updated test readme:  https://github.com/bilal-fazlani/commanddotnet/blob/master/CommandDotNet.Tests
