### ISSUE TITLE
Arguments after argument separator are not passed to method

### ISSUE THREAD

**Issue by drewburlingame** [bilal-fazlani/commanddotnet#123]
I've created a [this branch](https://github.com/bilal-fazlani/commanddotnet/pull/122) with failing tests.   

@bilal-fazlani I'd like feedback on the scenarios to see if we agree on the behavior and if there are any scenarios missing.  

If the feature is implemented as suggested in the tests, it will not be possible to determine which arguments were included after the separator.  Would that be important?  I could see it being helpful if they were going to be used to pass to another command, but I don't know if that's something we need to account for.

I have some thoughts on a couple of alternate, more explicit implementations.  I can't remember ever using or implementing this feature in the past so I may be missing something.  One of the problems we have now is that the arg separator will show up for every command whether it supports the feature or not.  I.E. whether it can capture and work with the extra args.  If the args are just going to be dropped, is it valid to accept them?  I think it would be cleaner to throw an exception in this case so users are aware the command is not working as they had expected.  And the help shouldn't include them in the usage example.  These implementations would solve that.

1. specify on the argument list if the feature is allowed. `[Argument(IncludeRemainingArguments=true)] List<string> argumentList)`
    * only allowed on the single argument list parameter and only if the type is string list.
2. capture in a separate list `[RemainingArguments] List<string> remaining)` 
    * this could exist with an argument list.
    * enables the method to distinguish between list arg and separated args.  I wonder if this is helpful for cases where the separate args are passed to another command.
3. both

**Comment by bilal-fazlani** [comment]
I have come across remaining arguments when using `dotnet run`
All the arguments you pass after `--` are passed to the actual app and all arguments before `--` are passed to `dotnet run`.   I also came across this when using `ScalaTest`

For this reason, I don’t like the name `RemainingArguments`. I am not sure what is a better name. 


Anyways, Option 2 -> `capture in a separate list [RemainingArguments] List<string> remaining)` seems attractive.

If I were to create such an app, I will find it intuitive if I could do it like this:

```c#
class Program
{
    static int Main(string[] args)
    {
       var appRunner = new AppRunner<MainApp>();
       return appRunner.Run(args);
    }
}

class MainApp
{
    void SomeCommand([Option] string someParam, [RemainingArguments] string[] remainingArgs)
    {
        var appRunner = new AppRunner<ChildApp>();
        appRunner.Run(remainingArgs);
    }
}

class ChildApp
{
    void AnotherCommand(int number, string name, string etc)
    {
        Console.WriteLine(number + name + etc);
    }
}
```

and use it like

`my-app.exe —some-param=abc — 2 bilal bla`

But this is just initial thought and I haven't thought through this.. what do you think..

And about what you said,

```C#
new Given<App>("exec - enabled - also list operand - extra args before and after separator - remaining args added to operand list ")
                {
                    And = {AppSettings = SeparatorEnabledBasicHelp},
                    WhenArgs = "ListPlusOne one a1 -- b2 c3",
                    Then =
                    {
                        Outputs =
                        {
                            new App.ListResults
                            {
                                One = "one",
                                Extras = new List<string> {"a1", "b2", "c3"}
                            }
                        }
                    }
                },
```
yeah this seems very odd. Ideally if `a1` is not expected it should just throw an exception or get ignored depending upon AppSettings.
Extras should be just `b2` and `c3`

I did not understand this part
>One of the problems we have now is that the arg separator will show up for every command whether it supports the feature or not. I.E. whether it can capture and work with the extra args. If the args are just going to be dropped, is it valid to accept them? I think it would be cleaner to throw an exception in this case so users are aware the command is not working as they had expected. And the help shouldn't include them in the usage example.

**Comment by drewburlingame** [comment]
> I don’t like the name RemainingArguments. I am not sure what is a better name.

I'm not a fan of it either.  I started with SeparatedArguments but didn't like it any better.  But thinking about it again, SeparatedArguments more clearly expresses the intent.  I think this is the simplest and clearest choice.  Devs can union the two lists if they don't care about the separation. 

> I will find it intuitive if I could do it like this:

Yeah, that's what I was thinking too.  In that case, there could be two lists, right?  A list before the separator and a list after the separator.

> Ideally if `a1` is not expected it should just throw an exception or get ignored depending upon AppSettings.

This depends on how we define the remaining arguments.  If there were two lists for this method, then `a1` would be added to the first list and `b2` would be added to the remaining args list.  If there was only one list that could also contain remaining args, then they'd both be added to the same list.

> One of the problems we have now is that the arg separator will show up for every command whether it supports the feature or not. I.E. whether it can capture and work with the extra args. If the args are just going to be dropped, is it valid to accept them? I think it would be cleaner to throw an exception in this case so users are aware the command is not working as they had expected. And the help shouldn't include them in the usage example.

If you look at the help examples, `[[--] <arg>...]` appears in the example for every command in the app, even if there's no list the args could be added to.  It's misleading.

**Comment by bilal-fazlani** [comment]
> Yeah, that's what I was thinking too. In that case, there could be two lists, right? A list before the separator and a list after the separator.

Yeah

> If you look at the help examples, [[--] <arg>...] appears in the example for every command in the app, even if there's no list the args could be added to. It's misleading.

Ohh, I was not aware of this problem. I see it now.

**Comment by bilal-fazlani** [comment]
Thinking in more detail about `[RemainingArguments] string[] remainingArgs`,

it should be possible to add it at multiple places, right? like this:

```c#
    class MainApp
    {
        private readonly string[] _remainingArgs;

        public MainApp([RemainingArguments] string[] remainingArgs)
        {
            _remainingArgs = remainingArgs;
        }
        
        void SomeCommand(string someParam, [RemainingArguments] string[] remainingArgs)
        {
            var appRunner = new AppRunner<ChildApp>();
            appRunner.Run(remainingArgs);
        }

        void AnotherCommand([RemainingArguments] string[] remainingArgs)
        {
            var appRunner = new AppRunner<ChildApp>();
            appRunner.Run(remainingArgs);
        }

        void anotherOneUsingGlobalOptions()
        {
            var appRunner = new AppRunner<ChildApp>();
            appRunner.Run(_remainingArgs);
        }
    }
```

**Comment by drewburlingame** [comment]
Yes, we could make it available for any method param or model property.  And since it's a special argument case, it should be ok to duplicate it in ctor and command methods.  Help will treat it differently as well.  

I think SeperatedArguments will be a better term for it since it's the arguments after the separator and 'argument separator' is a common enough term for this.  And I live in hope we'll wake up tomorrow with a better name.

**Comment by drewburlingame** [comment]
Based on this conversation, I think the work is:

1. remove AppSettings.AllowArgumentSeparator
1. introduce SeparatedArgumentsAttribute
1. update parsing
1. update help providers
1. update readme.md

does that sound correct to you @bilal-fazlani ?

**Comment by bilal-fazlani** [comment]
Agree

**Comment by drewburlingame** [comment]
After updating the parsing I realized we keep remaining arguments even if a separator wasn't used.  RemainingArguments is also the named used in other libraries so I think we should keep that name.  Everything else stays the same.

**Comment by drewburlingame** [comment]
This will be easier to implement in v3 because [ParseResult.cs](https://github.com/bilal-fazlani/commanddotnet/blob/beta-v3/master/CommandDotNet/Parsing/ParseResult.cs) keeps a list of remaining and separated arguments

``` c#

    public class ParseResult
    {
        public ICommand TargetCommand { get; }
        public IReadOnlyCollection<Token> RemainingArguments { get; }
        public IReadOnlyCollection<Token> SeparatedArguments { get; }
        public ArgumentValues ArgumentValues { get; }
```

There are two options to introduce this.  

Option 1: Add middleware that injects these values into attributed properties on the class.  This can be added now with low complexity.  The only downside is that it's not clear for middleware which commands within the class use these extra arguments.

Option 2: Depends on an enhancement that enables defining non-argument parameters.  This will be implemented to support middleware methods that will replace current ctor options.

**Comment by drewburlingame** [comment]
This is not needed with the beta3/master branch.  Command methods can include a CommandContext param and access these via commandContext.ParseResults.SeparatedArguments to get the tokens collection or commandContext.ParseResults.SeparatedArguments.ToArgArray to get the string array to pass to another command.
