### ISSUE TITLE
Proposed arguments terminology update

### ISSUE THREAD

**Issue by drewburlingame** [bilal-fazlani/commanddotnet#124]
When I was getting up to speed, I found the terminology for Argument and Parameter to be ambiguous at times marking it harder to understand the intent of some classes.  It was also not clear to me how 

I find the terminology and descriptions from these links to be helpful. 

> http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
http://www.informit.com/articles/article.aspx?p=175771

Summary:

* All non-command input is an argument.  
* There are 2 types of arguments: Operand, Option.  
  * **Operand**
    * Math definitions: 
      * "the object or quantity that is operated on"
      * "one of the inputs (quantities) for an operation"
    * always positional, never named
    * can be required or optional
  * **Option**
    * change the behavior of the operation
    * always named, never positional
    * can be required or optional
    * requires an option-value provided following the name
    * **Flags**
      * any option that is a boolean
      * can be clubbed
      * can be explicit (requires option-value) or implicit (no option-value) 

When defining arguments, we have 2 modes of definition:
* **Method Parameters**
  * including constructors, where only options can be defined
* **Model Properties**

If we follow this terminology, we remove the disambiguate the meaning for parameter and argument, making the code and documentation easier to read.

This will require some updates to code and documentation.  ArgumentMode.Parameter would be obsoleted and reference the new ArgumentMode.Operand.  I would be happy to update the documentation as well.

@bilal-fazlani what do you think?

**Comment by bilal-fazlani** [comment]
Honestly, half way through the project even I was confused.
I like the hierarchy you have proposed. This could be a lot of work though.

**Comment by drewburlingame** [comment]
Yeah, I think it will be a bit of work.  I'll add it to my list of things to play around with.  I feel like it's finally safe enough to play with.

**Comment by drewburlingame** [comment]
I've included these updates in the v3 branch
