### ISSUE TITLE
Rethinking IArgumentModel

### ISSUE THREAD

**Issue by drewburlingame** [bilal-fazlani/commanddotnet#125]
While writing the feature tests for IArgumentModel I realized the design does not guarantee a consistent order for the arguments.  .Net does not guarantee the order properties are reflected.  It's generally consistent but not guaranteed.   

Additionally, as a developer, I don't think about the order of properties in a class.  I wouldn't expect moving properties around within a class to break a contract.  The current design violates the principle of least surprise.  

When we think about methods, we understand that position is an integral part of the contract.  

Given that operands are only positional and options are only named, IArgumentModel is currently only well suited for Options.  To be suitable for operands, we'd need a new ArgumentAttribute (or OperandAttribute) that requires position when used on properties.  I wonder if it would be simpler & easier to let IArgumentModel only be used for options and force operands to be defined as method parameters.

thoughts @bilal-fazlani ?

What was the original intention for IArgumentModel?  Was it to enable fluent validators?

**Comment by bilal-fazlani** [comment]
Finally got some time to read this.. sorry for my late responses.

>.Net does not guarantee the order properties are reflected. It's generally consistent but not guaranteed.

I didn't know this!

> What was the original intention for IArgumentModel? Was it to enable fluent validators?

Yes. Exactly that.

> I wonder if it would be simpler & easier to let IArgumentModel only be used for options and force operands to be defined as method parameters.

This will solve this issue. But it will take away fluent validations from operands.

> IArgumentModel is currently only well suited for Options. To be suitable for operands, we'd need a new ArgumentAttribute (or OperandAttribute) that requires position when used on properties.

I wish we could do something without adding any responsibility to app devs... not sure what at this moment..

**Comment by drewburlingame** [comment]
This is mostly theoretical.   We can wait until someone raises it as an issue or we come up with an ideal solution.  Maybe it's worth calling out in the documentation?

If we wanted to address this in a backward compatible fashion, I think we add an optional Argument.Position property that can be used in cases when needed, but mostly ignored.

On the topic of validation: I think validation should be a middleware.  Fluent validations would be one option.  Another would be System.ComponentModel.DataAnnotations which would work for both property and parameter.  DataAnnotations cover a lot of scenarios and also make it easy to provide hints in the help output.    It's too bad there isn't an option to declare validations for methods using expressions.
