### ISSUE TITLE
Possible breaking change in 2.8.0

### ISSUE THREAD

**Issue by disklosr** [bilal-fazlani/commanddotnet#143]
So I updated from 2.7 to 2.8 and things stopped working:

```
Unhandled Exception: System.TypeLoadException: Could not load type 'CommandDotNet.IoCExtension' from assembly 'CommandDotNet, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null'.
   at CommandDotNet.IoC.MicrosoftDependencyInjection.Extension.UseMicrosoftDependencyInjection[T](AppRunner`1 appRunner, IServiceProvider serviceProvider)
   at MyAssembly.Bootstrap()
   at MyAssembly.Main(String[] args)
```

It seems that [this commit](https://github.com/bilal-fazlani/commanddotnet/commit/edd6382ac3f9cbf6e8bd17f0b2d1ad811806509d#diff-f8ec26c55916c1bd4de6ceee0f36551a) has changed `UseDependencyResolver` definition from being an extension method to an instance method of object `AppRunner`.

The class `IoCExtension` where the extension method was defined no longer exist, which breaks other nugets depending on its existence like `CommandDotNet.IoC.MicrosoftDependencyInjection`

**Comment by disklosr** [comment]
An easy workaround is to change
```csharp
new AppRunner<App>().UseMicrosoftDependencyInjection(serviceProvider);
```
to
```csharp
new AppRunner<App>().UseDependencyResolver(new MicrosoftDependencyInjectionResolver(serviceProvider))
```

**Comment by drewburlingame** [comment]
I forgot about that nuget package.  I'll revert the change and push another package to restore the behavior.  Thanks for the heads-up @disklosr

**Comment by drewburlingame** [comment]
https://www.nuget.org/packages/CommandDotNet/2.8.1

**Comment by drewburlingame** [comment]
@bilal-fazlani can you remove the 2.8.0 package to prevent anyone from grabbing that package?

**Comment by disklosr** [comment]
Great! Thanks for addressing this issue.

**Comment by bilal-fazlani** [comment]
2.8.0 removed from nuget.

For any breaking changes, let's increment major version to 3.x.x

**Comment by drewburlingame** [comment]
Agreed.  I'm avoiding them at all costs.  This one snuck past me.

**Comment by drewburlingame** [comment]
And thanks for removing that.
