### ISSUE TITLE
Extract advanced documentation from readme

### ISSUE THREAD

**Issue by drewburlingame** [bilal-fazlani/commanddotnet#147]
The readme.md is getting long and it's cumbersome to add complex examples.   What do you think of moving most of the documentation to an easier to manage & grok format?

I was thinking Github Wiki or Github Pages or readthedocs.org, but maybe there's something else out there that's better?

### [Github Wiki](https://github.com/bilal-fazlani/commanddotnet/wiki)

pros:
* uses markdown
* simple to update pages
* easy to navigate
* free

cons:
* documentation not in repo, not synced with dev branches

### [Github Pages](https://pages.github.com)

pros:
* uses markdown
* documentation in repo, synced with dev branches
* easy to navigate
* free

cons:
* requires ruby + Jekyl to view/debug locally

### [ReadTheDocs](https://readthedocs.org)

pros: 
* uses markdown (follows commonmark, same as GitHub)
* documentation in repo, synced with dev branches
* easy to navigate
* free

cons:
* requires python + Sphinx

option to consider:

Supports richer documentation if you use restructuredText and a lot of extensions, but with a higher learning curve.   We don't have to use restructuredText with this so we just need to determine if we want to accept it.

> edit: it looks like Github Wiki + Pages supports markdown, restructuredText and asciidocs by default so I don't think ReadTheDocs poses any additional complexity in that regard

**Comment by bilal-fazlani** [comment]
I have used github pages earlier. liked it for it's simplicity, themes & free & automatic hosting.

Github wiki is also good but it's not versioned I guess. 

I have not used ReadTheDocs before so I don't have an opinion on that. the website looks good and promising. Does it provide anything that github pages doesn't ?

**Comment by drewburlingame** [comment]
I haven't used GHP or RTD but after looking into them, it looks like they're the same except one uses Ruby + Jekyl  and the other uses python + Sphinx.  I think the choice is based on which one we're more comfortable with.  Since you know you're happy with GHP I think we should use that.  Is that something you'd be able to setup?

**Comment by bilal-fazlani** [comment]
Ok, Sure. I will set it up tonight. 👍

**Comment by bilal-fazlani** [comment]
Alright, so I went on a completely different path 😄   https://docsydocs.netlify.com/
I am using it as theme with hugo. I have used hugo before and found it to be good. Provides a lot of flexibility and looks very neat. 

I will push something soon, it wont be a beginning, we should be able to migrate our existing doc section by section then.

**Comment by bilal-fazlani** [comment]
The sample doc is now available at https://bilal-fazlani.github.io/commanddotnet/
I will slowly populate the actual content. 

I might also give readthedocs a try later

**Comment by drewburlingame** [comment]
Looks great.  Thank you!

**Comment by bilal-fazlani** [comment]
Explored more on this. 
At this point I find RTD with MkDocs very attractive. It supports markdown so our docs can be ported easily (hopefully) . And it supports multiple themes.

I like this theme:  https://github.com/squidfunk/mkdocs-material

**Comment by bilal-fazlani** [comment]
It'd done. 
https://bilal-fazlani.github.io/commanddotnet/

the disqus comments plug in is not working for some reason. will take a look tomorrow or later

**Comment by drewburlingame** [comment]
That looks great.  

A typo I noticed: https://bilal-fazlani.github.io/commanddotnet/attributes/#__comments  `-p \| --planet` should be `-p | --planet`

**Comment by drewburlingame** [comment]
Is it possible to add more structure to the menu bar on the left?  It would be nice to separate advanced scenarios from mainline scenarios.  Maybe something like: https://simpleinjector.readthedocs.io ?

**Comment by bilal-fazlani** [comment]
It is possible. I just don't have any structure in mind .. 
can you think of some specific hierarchy ?

**Comment by drewburlingame** [comment]
Maybe something like this?

* Introduction
* Quick Start
* Defining Commands
  * Parameters
  * Attributes
  * Constructors
  * Default Method
  * Default Values
  * Collections
  * Argument Models
  * Async Methods
  * Custom Return Codes
  * Nesting commands
  * Exceptions
* Extras
  * Directives
  * Fluent Validation
  * Settings
* Extensibility
  * Dependency Injection
  * Help Providers
  * Custom Interceptors

**Comment by bilal-fazlani** [comment]
Looks good. Will make the changes

**Comment by bilal-fazlani** [comment]
I have pushed the changes. things look better to me now.
Take a look. We can close this if you think it looks ok

**Comment by drewburlingame** [comment]
It was looking great.  We can close it.  I'll be reviewing all docs as a part of #150  and can update them then.

**Comment by bilal-fazlani** [comment]
Ok cool.
