### ISSUE TITLE
NullReferenceException in ModelValidator

### ISSUE THREAD

**Issue by SebastianStehle** [bilal-fazlani/commanddotnet#169]
Hi,

it just got a pull request: https://github.com/Squidex/squidex-samples/pull/33

It seems that some of my validators are not picked up correctly and therefore CommandDotNet  throws a NullReferenceException

**Comment by freakingawesome** [comment]
Copying my further comment about the origin:

> I think a breaking change snuck into CommandDotNet during [this set of changes](https://github.com/bilal-fazlani/commanddotnet/commit/7c4b46675a74938f9112405e74b2a4951b0b7cb0) three months ago.
> 
> The NullReferenceException was [blowing up on this line](https://github.com/bilal-fazlani/commanddotnet/blob/master/CommandDotNet/ModelValidator.cs#L43). I suspect it's something in the newer `TryResolve` function that's tripping things up.

**Comment by drewburlingame** [comment]
It looks like I only added a test to ensure the validator was created if there was no DI, but missed the case there is a DI but the type is just not registered.  I'll fix that tomorrow in both master and the V3 branch.

@SebastianStehle thanks for creating the issue.

@freakingawesome thanks for the investigation.  The links were helpful.

**Comment by drewburlingame** [comment]
I've pushed 2.8.2 with the fix

**Comment by freakingawesome** [comment]
@drewburlingame - Thanks for the fix but I [don't see v 2.8.2 listed on nuget.org yet](https://www.nuget.org/packages/CommandDotNet/).

**Comment by drewburlingame** [comment]
Thanks for the heads up.  The deploy step failed on the build because I used the old tagging pattern.  The [build has passed](https://travis-ci.com/bilal-fazlani/commanddotnet/jobs/241488550) now and says the package was pushed.  It can take a while for it to show up in nuget.org.

**Comment by drewburlingame** [comment]
https://www.nuget.org/packages/CommandDotNet/2.8.2
