### ISSUE TITLE
Inherited options behavior clarification

### ISSUE THREAD

**Issue by drewburlingame** [bilal-fazlani/commanddotnet#176]
@bilal-fazlani  I want to make sure I understand this feature correctly.  Currently, when an option is inherited, it looks like values can be provided in the parent command and the target command.  The option is shown in the help for both commands.  If the option is provided for both commands, the parser fails while parsing the second instance.  This isn't standard behavior in any tool I've used and I don't think the behavior is obvious to a user.  What was the intent of this feature?  Would it make sense to only show inherited options in the help for the ~parent~ child command and also to only accept them in the ~parent~ child command?

**Comment by drewburlingame** [comment]
@bilal-fazlani I corrected my last question above.  This is the last thing I want to clean up before the release because I think the user experience is not clear.  It's not obvious when options for a command can be used for subcommands and it's also not obvious when options can be used in subcommands.  We can solve the latter by only displaying inherited options in executable subcommands.  The former is only a problem when a default method is used to make parent commands executable.  In those cases, we could display the options separately.  What do you think?

**Comment by bilal-fazlani** [comment]
Yes, The inherited feature has been very ambiguous since the beginning. I just ported it as is from Microsoft library. 

I agree with your suggestion.

**Comment by drewburlingame** [comment]
Ok, we're on the same page then.  I'm thinking it would be more clear to obsolete the term `Inherited` and replace it with `UseOnlyInExecutableSubcommands`.  Option.Parent will still be the defining command, not the executable command, and the option will still be in the Command.Options lists for defining command and the executable subcommands. Does that seem more clear to you?
