### ISSUE TITLE
Formatting of help (Line: Usage)

### ISSUE THREAD

**Issue by asymetrixs** [bilal-fazlani/commanddotnet#179]
Hi,

I was wondering about the following. When I generate a console application I compile everything into an executale (on Linux <filename>, on Windows probably <filename>.exe).
However, running my program with --help shows me the help but in the first line it says:
    Usage: dotnet <filename>.dll [options] [command]

It would be much better to resolve that to the actual file name, like:
    Usage: <filename> [options] [command]
or
    Usage: <filename>.exe [options] [command]

This way users will be less confused about the 'dotnet' and the '.dll'.

**Comment by drewburlingame** [comment]
Hi @asymetrixs 

I think the default behavior is confusing and I'd like to change it but don't want to introduce breaking changes.  If you have defined an ApplicationMetadata.Name for the root command.  You can fix this in two ways.

1) do not define ApplicationMetadata.Name for the root command
2) set AppSettings.Help.UsageAppNameStyle = UsageAppNameStyle.Executable

**Comment by asymetrixs** [comment]
Using UsageAppNameStyle.Executable left me with '<filename>.dll' even though on Linux it does not have the .dll suffix if I compile it with "<OutputType>Exe</OutputType>"

However, you pointed me in the right direction.
Using UsageAppNameStyle.GlobalTool and [ApplicationMetadata(Name = "<filename>")] on the class that represents the menu worked fine.
Thanks

**Comment by drewburlingame** [comment]
Thanks for the feedback.  I'm curious about how your app is structured.  The method below is used to get the filename and so I'd expect ".exe" if run from a .net executable.  How are you compiling everything into the executable?

``` cs

        private static string GetAppFileName()
        {
            var hostAssembly = Assembly.GetEntryAssembly();
            return hostAssembly == null 
                ? null 
                : Path.GetFileName(hostAssembly.Location);
        }
```

**Comment by asymetrixs** [comment]
I compile it more or less like this
`
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
</Project>
`

`dotnet build` on RHEL 7 which gives me an executable without a file extension.

**Comment by drewburlingame** [comment]
Given this is a .net issue and we have a workaround for you, I'll close this issue.  I may make the default usage not include the app name to avoid the need for the workaround.
