### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by mustafmst** [bilal-fazlani/commanddotnet#185]
Could You add info on what license You want to provide this framework?
I think it's great but by the law I can't use it if it hasn't got license.

I really like [beerware](https://en.wikipedia.org/wiki/Beerware) ;)

**Comment by drewburlingame** [comment]
@bilal-fazlani do you have a particular license in mind?

**Comment by bilal-fazlani** [comment]
I was thinking of MIT

**Comment by bilal-fazlani** [comment]
@Drew, what are your thoughts?

**Comment by drewburlingame** [comment]
I was thinking MIT too.

**Comment by drewburlingame** [comment]
@mustafmst we added an MIT license in https://github.com/bilal-fazlani/commanddotnet/pull/189
