### ISSUE TITLE
Expand argument names in help usage example

### ISSUE THREAD

**Issue by taori** [bilal-fazlani/commanddotnet#186]
![grafik](https://user-images.githubusercontent.com/5545184/73610817-bd0b2500-45db-11ea-8cdc-1d1de2c48e61.png)

since arguments are not optional it would make sense to utilize them in the usage text if they received Argument attributes.

So for this signature 
![grafik](https://user-images.githubusercontent.com/5545184/73610863-3276f580-45dc-11ea-8f43-fc26a4764f40.png)

I would expect a usage text like specified in "Syntax" or `nuget-unlister list prereleasebefore [package] [version] [--options]`

**Comment by drewburlingame** [comment]
I've thought the same thing and it's an option I've planned to add sometime after I've completed the v3 documentation.  In the meantime, using v3 you can subclass HelpTextProvider and override UsageOperand to get the desired behavior.

**Comment by taori** [comment]
Yes, i did attempt to use it but did not find documentation on it, prototyped some and did not get a solution which i was happy with. Since syntax imo belongs in the default help text too, given that is provided in this case, i figured this behavior should be changed one way or another.

also the dotnet tool has a neater syntax to indicate arguments (angle brackets).

Also it plays back your own input, instead of just showing you the syntax, which seems like another benefit.

See
![grafik](https://user-images.githubusercontent.com/5545184/73613897-5e08d880-45fa-11ea-8393-2a7f572116b4.png)

**Comment by drewburlingame** [comment]
Yeah, the documentation is still in progress. I've just been able to pick it up again this last week.  

I like the angle brackets for the argument names in the usage.

What do you mean by

> Also it plays back your own input, instead of just showing you the syntax, which seems like another benefit.

**Comment by drewburlingame** [comment]
I've [documented the help](https://bilal-fazlani.github.io/commanddotnet/V3/Extensibility/help/)

**Comment by taori** [comment]
> What do you mean by
> 
> > Also it plays back your own input, instead of just showing you the syntax, which seems like another benefit.

Well what i meant by that is that it shows you the values you inserted at which argument. But i guess having syntax being displayed or docs for the help provider would already be a good start :)

**Comment by drewburlingame** [comment]
> Well what i meant by that is that it shows you the values you inserted at which argument

I don't see your input in the help in the example you showed.  Am I missing it?

**Comment by taori** [comment]
i think i misinterpreted the screenshot - effectively it only shows the command call syntax until then, which obviously `dotnet install` etc. So yeah - just adding syntax + angle brackets would already solve this just fine i think.
