### ISSUE TITLE
Support comma separated multiple values

### ISSUE THREAD

**Issue by bilal-fazlani** [bilal-fazlani/commanddotnet#19]

**Comment by bilal-fazlani** [comment]
Does't seem valid anymore

**Comment by drewburlingame** [comment]
@bilal-fazlani I think this would be a handy feature.  I've almost added it a few times but kept putting it off to work on other things.  It would just be a matter of splitting the values here https://github.com/bilal-fazlani/commanddotnet/blob/master/CommandDotNet/ClassModeling/BindValuesMiddleware.cs#L47 in 

```csharp
 if (argument.InputValues.Any())
{
    if (!SetFromStringInput(argument, argument.InputValues.SelectMany(iv => iv.Values.SelectMany(v => v.Split(','))))
    {
        return false;
    }
}
```

It would probably be best to add an AppSettings.AllowCommaSeparatedListValues
