### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by drewburlingame** [bilal-fazlani/commanddotnet#190]
Documentation for V3 is nearly complete and could use some reviews.  I'd appreciate anyone taking a look through the docs and pointing out mistakes or where something could be more clear or more to the point.  

https://bilal-fazlani.github.io/commanddotnet/V3/

**Comment by drewburlingame** [comment]
@bilal-fazlani if you have time ^

**Comment by bilal-fazlani** [comment]
Sure, I will go through the docs

**Comment by bilal-fazlani** [comment]
This link https://bilal-fazlani.github.io/commanddotnet/ seems to be broken 

![image](https://user-images.githubusercontent.com/3396271/74601405-0cfde780-50c4-11ea-9f15-40b552b404d9.png)

The url https://bilal-fazlani.github.io/commanddotnet/ is already cached by google

![image](https://user-images.githubusercontent.com/3396271/74601469-c9f04400-50c4-11ea-9aad-a0e56e74b44c.png)

I think we should add a redirect from This link https://bilal-fazlani.github.io/commanddotnet/ to This link https://bilal-fazlani.github.io/commanddotnet/V2 . later we can change the redirection to V3

I can take this up.

**Comment by bilal-fazlani** [comment]
Will continue to review the doc contents and hopefully finish today or in few days

**Comment by drewburlingame** [comment]
Looks like I missed a test with the V2 doc move.  I'll revert to the working version and then get it fixed.  Thanks for working on it.

**Comment by bilal-fazlani** [comment]
Ohh I have added a redirect. It works fine now.

**Comment by drewburlingame** [comment]
I've been getting a 404 when I go there.  Even with the redirect to the v2 path

**Comment by bilal-fazlani** [comment]
I suspect browser has cached 301 permanent move. Can you try it with a different browser?

**Comment by bilal-fazlani** [comment]
oops, looks like its broken again.

**Comment by drewburlingame** [comment]
yeah.  i pushed another change so I've just pushed the revert and will try again after the build

**Comment by drewburlingame** [comment]
Sorry about that.  I tested all the links worked within the v2 and v3 folders but missed the test from root.

**Comment by bilal-fazlani** [comment]
no problem :). i actually broke it further 😛. 
![image](https://user-images.githubusercontent.com/3396271/74603802-3d05b480-50dd-11ea-8c52-ad72fd7fb39f.png)

it should get fixed after the revert hopefully.

**Comment by drewburlingame** [comment]
my changes today didn't fix it.  still 404.  I'll put an index.md in the root.

**Comment by bilal-fazlani** [comment]
it doesn't work from browser for me but works from curl:

```
curl -sSL -D - https://bilal-fazlani.github.io/commanddotnet/ -o /dev/null
```

**Comment by drewburlingame** [comment]
I also noticed that when I serve it locally now, it's in a continuous build loop.  I'm not sure what caused that.  I'll look into that too.

**Comment by drewburlingame** [comment]
the redirect works locally. I wonder if 301 is cached on a router.

**Comment by bilal-fazlani** [comment]
if routers cache 301, then it would be one hell of a problem for websites!

btw, i think a lot of conversations we have are like chat. 
Discord is fairly popular these days and may be better than gitter. Let's give it a try?
https://discord.gg/GYYmGB

**Comment by drewburlingame** [comment]
Ugh, found it.  

I needed  https://bilal-fazlani.github.io/commanddotnet/  
not https://bilal-fazlani.github.io/

I'll be making no further commits today !!!  I've got the dumb.

**Comment by drewburlingame** [comment]
There's only one piece of documentation I'd still like to add which is around middleware best practices, but I don't think it is needed for the release.  If the documentation looks good, I think we're ready to release v3 to master.

**Comment by bilal-fazlani** [comment]
Sure. I have started reviewing the docs. Will keep you updated on it. 

btw, please ignore the discord link I sent earlier. I used my office email address for that. this one is correct. https://discord.gg/aFh9ms

We can discord if it works for a general chat for everyone. I have seen people use slack and gitter too. Let me know what you think

**Comment by bilal-fazlani** [comment]
You have added excellent features @drewburlingame 👍 

I am making myself familiar with the new features using v3 documentation. I am going a bit slow and will take few days to finish the review. I will keep posting some feedback suggestions on this github issue.

**Comment by bilal-fazlani** [comment]
https://bilal-fazlani.github.io/commanddotnet/V3/Middleware/response-files/#response-files

`response-files` is an awesome feature.  Should we call this feature "argument-files" ? or something similar..? Maybe my reason to think of it as "argument-files" is that we are providing first class support for reading arguments from a file but - not for writing response of program. Plus it is a file with a bunch of arguments :P

**Comment by bilal-fazlani** [comment]
https://bilal-fazlani.github.io/commanddotnet/V3/Extensibility/help/#help 
awesome work on the help configuration 👍

**Comment by drewburlingame** [comment]
> https://bilal-fazlani.github.io/commanddotnet/V3/Middleware/response-files/#response-files
> 
> `response-files` is an awesome feature. Should we call this feature "argument-files" ? or something similar..? Maybe my reason to think of it as "argument-files" is that we are providing first class support for reading arguments from a file but - not for writing response of program. Plus it is a file with a bunch of arguments :P

I agree, it's very useful. It's an established pattern with that name. MS uses them in a lot of their tools.  I believe the name is because the files were generated as responses from one application to be used in other applications.

**Comment by bilal-fazlani** [comment]
Okay.
