### ISSUE TITLE
V3 Microsoft Dependency Injection 

### ISSUE THREAD

**Issue by dotnetshadow** [bilal-fazlani/commanddotnet#196]
Hi there,

Great work to getting to v3. 

I'm trying to upgrade a console app from v2 to v3 but I'm having difficulty when using dependency injection.

I'm getting the following error:
`Exception Message:   No service for type 'Foo.Commands.InfoCommand' has been registered.
Exception Source:    Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService - System.Object GetRequiredService(System.IServiceProvider, System.Type)
Runtime terminating: True`

It seems I need to register the Commands now is that right?

**Comment by dotnetshadow** [comment]
I solved it, just realised I need to add

`.AddTransient<InfoCommand>()`

Should I be using scope or transient here?

**Comment by drewburlingame** [comment]
> It seems I need to register the Commands now is that right?

Yes, you should register the commands now.  You can use the `appRunner.GetCommandClassTypes` extension method to make that easier.

> Should I be using scope or transient here?

Disclaimer: I'm not very familiar with the MS container, just enough to implement Resolve and TryResolve :)  
From how I know transient to work in other containers, it should be fine since we will only resolve the command class once.  There wouldn't be multiple instances of it.

**Comment by drewburlingame** [comment]
Let me know if there are any other upgrade issues.  We're also active on [Discord](https://discord.gg/QFxKSeG) for any questions or comments.

**Comment by dotnetshadow** [comment]
@drewburlingame Cheers, thanks for confirming. Just need to work out how MS container can loop through and register these. I don't think it natively does this might need to use a nuget package

**Comment by drewburlingame** [comment]
@dotnetshadow would this do the trick?

```c#
var commandClassTypes = new AppRunner<App>().GetCommandClassTypes();
foreach (var type in commandClassTypes)
{
	serviceCollection.AddTransient(type);
}
```

**Comment by drewburlingame** [comment]
@dotnetshadow can we close this issue?

**Comment by dotnetshadow** [comment]
@drewburlingame yes that's fine thank you
