### ISSUE TITLE
FluentValidation version 8 upgrade

### ISSUE THREAD

**Issue by htanbw** [bilal-fazlani/commanddotnet#204]
Is there a timeline to upgrade the FluentValidationMiddleware to use the latest version of FluentValidation? There are breaking changes affecting the use of ValidatorAttribute between version 7.x and version 8 - https://docs.fluentvalidation.net/en/latest/upgrading-to-8.html#validatorattribute-and-attributedvalidatorfactory-have-been-moved-to-a-separate-package

We have project dependencies using version 8 of FluentValidation.

**Comment by drewburlingame** [comment]
@htanbw I updated to v8.0.0.  I didn't want to force a later version if not necessary.  Can you check the CommandDotNet.FluentValidation.2.0.0-preview1 nuget and let me know if it works for you?

**Comment by htanbw** [comment]
@drewburlingame Thank you for the quick turnaround. The preview package works beautifully with my project.

**Comment by drewburlingame** [comment]
great. the new package is released.
