### ISSUE TITLE
Update documentation re: UsageAppName and overriding it

### ISSUE THREAD

**Issue by bilal-fazlani** [bilal-fazlani/commanddotnet#227]
Give the following code:

```c#
[Command(Usage = "fake-git")]
class Git
{
    [SubCommand]
    public Stash Stash { get; set; }
}
class Stash
{
    [DefaultMethod]
    public void StashChanges()
    {
        Console.WriteLine("lalala");
    }
    
    public void List()
    {
        Console.WriteLine("list");
    }
}
```

When I execute:
`dotnet run -- -h` from my example project,

I see the following output

![image](https://user-images.githubusercontent.com/3396271/77995557-a407c180-7349-11ea-8f6a-1a18b8f2a40b.png)

But when I execute `dotnet run -- stash -h`, I see that printed usage is not respecting the hardcoded usage by developer.

![image](https://user-images.githubusercontent.com/3396271/77995608-c3065380-7349-11ea-96c0-76ed614ae241.png)

**Comment by drewburlingame** [comment]
You're looking for new AppSettings { Help = { UsageAppName = "fake-git" } }

Usage is a way to override the usage example for a command.  For example, to provide multiple examples of a usage.  See the [CancelMe](https://github.com/bilal-fazlani/commanddotnet/blob/master/CommandDotNet.Example/Commands/CancelMe.cs#L10) example command

**Comment by drewburlingame** [comment]
I think the work here would be to make the documentation more clear.

**Comment by bilal-fazlani** [comment]
Thanks @drewburlingame .

**Comment by drewburlingame** [comment]
If we keep this open, do you mind updating the title to better describe the work?

**Comment by drewburlingame** [comment]
@bilal-fazlani  I update some documentation for this.  Let me know if you think it's enough.  If not, what else do you think needs to change?  I think I'm too close to it to see.

**Comment by bilal-fazlani** [comment]
Docs loog good. Closing the issue
