### ISSUE TITLE
Dependency Injection example?

### ISSUE THREAD

**Issue by dotnetshadow** [bilal-fazlani/commanddotnet#27]
Hi there, 

Great library, I was wondering how you could use dependency injection when calling

`AppRunner<Calculator> appRunner = new AppRunner<Calculator>();`?

I would like to inject a class in my Calculator class how would I go about doing that?
  

``` 
    class Program
    {
        static int Main(string[] args)
        {          
            //  setup our DI
            var services = new ServiceCollection();            
            services.AddTransient<IHelloService, HelloService>();      
            var serviceProvider = services.BuildServiceProvider();
           
            // ---------------------------------------------------
           // Not sure how to use this ??? 
            var app = serviceProvider.GetService<Calculator>();
            //app.Run(args);
            ///------------------------------------------------

            AppRunner<Calculator> appRunner = new AppRunner<Calculator>();
            return appRunner.Run(args);
        }
    }
```

Example of what I'm trying to implement:
https://github.com/NLog/NLog.Extensions.Logging/wiki/Getting-started-with-.NET-Core-2---Console-application

**Comment by bilal-fazlani** [comment]
Interesting!
Nope. No provision yet. It will have to be done manually for now. But definitely worth putting effort I guess. I try to incorporate this.

**Comment by dotnetshadow** [comment]
Thanks for getting back to me, when you say you would have to do it manually for now, could you explain what I would have to do?

**Comment by bilal-fazlani** [comment]
I meant no dependency injection is possible. If one of the methods of Calculator needs an Instance of HelloService, you will have to create that instance manually within that method... or in the constructor of Calculator.

I thinking about providing property injection in the next release.. which should solve this problem.

**Comment by dotnetshadow** [comment]
Ahh ok I understand, so I would have to call  
`var app = serviceProvider.GetService<IMyService>();` from within the constructor makes sense

Would you be providing constructor or property instructor?

And sorry to ask but would you know when you might expect to support this?

**Comment by bilal-fazlani** [comment]
I would provide property injection at first. Constructor injection will be mess as constructor is already used for options. 

I can't promise, but I thinking in one week I should be able to do this.

**Comment by dotnetshadow** [comment]
Nice well done on providing such a great library, I look forward to testing this when released.

**Comment by dotnetshadow** [comment]
@bilal-fazlani Thank you so much for this feature. I can't believe how quick you have been able to implement it. I'll give it a go today and report back if I find any issues. Well done amazing 👍

**Comment by dotnetshadow** [comment]
@bilal-fazlani I've tried using your new nuget package
`<PackageReference Include="CommandDotNet" Version="0.5.14-alpha" />`

But I can't seem to use **using CommandDotNet.IoC.MicrosoftDependencyInjection;**

![image](https://user-images.githubusercontent.com/296247/34701277-626bc6a6-f53b-11e7-8ce2-0704dcddb429.png)

**Comment by bilal-fazlani** [comment]
I have written all the code and its tests. Just need to release a separate
nuget package for this feature. Will do it in couple of hours and let you
know.

**Comment by dotnetshadow** [comment]
Ahh I see, thanks for that, I have been testing it and it seems to be working well. 

I now understand by what you mean as property injection
One area where it caused a little pain was in the following situation

`public IOptions<AppSettings> AppSettings { get; set; }

        public ILogger<MyApplication> Logger { get; set; }

        private AppSettings Settings => AppSettings.Value;`

I have to declare settings twice if I want to read the value quickly, but I can work around it

**Comment by bilal-fazlani** [comment]
I am not sure if I understand what you mean by "declare settings twice if I want to read the value quickly" ..
Could you explain more please

**Comment by bilal-fazlani** [comment]
btw, here's the package:
https://www.nuget.org/packages/CommandDotNet.IoC.MicrosoftDependencyInjection/

**Comment by bilal-fazlani** [comment]
Readme is updated now: https://github.com/bilal-fazlani/commanddotnet#dependency-injection

**Comment by dotnetshadow** [comment]
Firstly thank you so much for getting this up 👍 

Secondly, sorry what I meant is that I have to inject my AppSetttings class as follows:

`public IOptions AppSettings { get; set; }`

But when I want to read a value from it I need to access such as:
`AppSettings.Value.MyVariable`

In constructor injection I usually do the following:

```
private class Foo() {
   private readonly AppSettings _settings;
   Foo(IOptions<AppSettings> settings) {
       _settings = settings.Value <---
   }
}
```
I was trying to figure out how I would go about doing that with the property injection

**Comment by bilal-fazlani** [comment]
```
serviceCollection.AddOptions();
serviceCollection.Configure<MySettings>(configuration);
serviceCollection.AddSingleton<MySettings>((sp) => sp.GetService<IOptions<MySettings>>().Value);
```

and 
```
    public class App
    {        
        public MySettings MySettings { get; set; }

        public void SayHi()
        {
            Console.WriteLine($"Hello {MySettings.Name}");
        }
    }
```

**Comment by temelj** [comment]
Do you have any intention to support "Constructor Injection" in the near future?
