### ISSUE TITLE
Usage for commands with subcommands should show example with and without the subcommand

### ISSUE THREAD

**Issue by bilal-fazlani** [bilal-fazlani/commanddotnet#28]

**Comment by bilal-fazlani** [comment]
Re-opening this issue. 
Help does not mention anything about default method. 

![image](https://user-images.githubusercontent.com/3396271/77995261-13c97c80-7349-11ea-9d88-09959c98793c.png)

compared to actual git cli where it shows that there is a a default action taken when no command is passed

![image](https://user-images.githubusercontent.com/3396271/77995318-3196e180-7349-11ea-8a10-db3d76cd98f1.png)

**Comment by drewburlingame** [comment]
what would you expect it to show without giving it a description?  do you plan to have it show usage example for every subcommand?  I could see that being helpful

**Comment by drewburlingame** [comment]
I think this is a feature or enhancement, not a bug.  It's showing the usage as expected.  If you added arguments and/or description etc, they would show the same as for any other command.

**Comment by bilal-fazlani** [comment]
I am not sure how to solve this yet. 
One thing I can think of is displaying the description of parent command if there is one. Git does the same.

```bash
Usage: 
  fake-git stash         Stash the changes in a dirty working directory away
  fake-git stash [command]

Commands:

  list

Use "fake-git stash [command] --help" for more information about a command.
```

If no description is given we can still display that there is a default action 


```bash
Usage: 
fake-git stash
fake-git stash [command]

Commands:

  list

Use "fake-git stash [command] --help" for more information about a command.
```

**Comment by drewburlingame** [comment]
I see your point.  It's a bit confusing since square brackets can mean the command is optional, but we don't consistently use them that way.  

If there were options and arguments, would it look like this?

```
Usage:
fake-get stash [options] [arguments]
fake-get stash [command]
```

or when there are interceptor options

```
Usage:
fake-get stash [options] [arguments]
fake-get stash [options] [command]
```

**Comment by bilal-fazlani** [comment]
I am not sure if default method supports options or arguments. Does it?
What are interceptor options?

**Comment by bilal-fazlani** [comment]
Ohh I see https://commanddotnet.bilal-fazlani.com/Extensibility/interceptors/

**Comment by bilal-fazlani** [comment]
Ok default method does seem to support args https://commanddotnet.bilal-fazlani.com/DefiningCommands/commands/#default-method

**Comment by bilal-fazlani** [comment]
> If there were options and arguments, would it look like this?

```
Usage:
fake-get stash [options] [arguments]
fake-get stash [command]
```

Yes. 

> or when there are interceptor options

```
Usage:
fake-get stash [options] [arguments]
fake-get stash [options] [command]
```
Yes if `fake-get stash [options] [command]` is already implement then it makes sense I guess

**Comment by bilal-fazlani** [comment]
This would look good if devs provide description

**Comment by drewburlingame** [comment]
the change would be in HelpTextProvider.SectionUsage

**Comment by bilal-fazlani** [comment]
I am finding it too difficult to modify help. I feel like a templating engine would have been better approach for help generation. Right now it feels too complicated.

**Comment by drewburlingame** [comment]
a templating engine would be the holy grail.  I thought about implementing a scaled-down version to avoid external dependencies but then decided against it.

**Comment by drewburlingame** [comment]
PR #232 will implement what you asked for.  I didn't fix any tests so you can review them to see the difference.  Most helpful will be the tests in the ClassCommands folder.

Without descriptions, the usage is still confusing, possibly more so in some cases.  With description, I don't think this change makes much of a difference.

**Comment by drewburlingame** [comment]
@bilal-fazlani what's your thinking on this issue these days?  Do we still need it and if so, what will it do?  

I was thinking we could create two different issues:

* AppHelpSetting to include subcommand usage similar to git synopsis
* AppHelpSetting to include interceptor options for parent commands in usage.

**Comment by bilal-fazlani** [comment]
> AppHelpSetting to include subcommand usage similar to git synopsis

Yes let's create an issue for this. Let's also discuss if we really need a setting for that. If yes, what should be the default.

> AppHelpSetting to include interceptor options for parent commands in usage.

Yeah, let's create an issue for it. Not sure about the details or priority of it though.

**Comment by drewburlingame** [comment]
> AppHelpSetting to include subcommand usage similar to git synopsis
> Yes let's create an issue for this. Let's also discuss if we really need a setting for that. If yes, what should be the default.
I see it as a feature that's disabled by default.  Something like: `new AppSettings{Help = {IncludeUsageOfSubcommands = true}}`

> AppHelpSetting to include interceptor options for parent commands in usage.
> Yeah, let's create an issue for it. Not sure about the details or priority of it though.
This is helpful in a couple of ways.  When viewing a command, it's more obvious which of the parent commands options are still available.  This is if we break out the options.  When a parent command has a default method that also has options, those options are not available for subcommands.  When viewing the help of one of those commands, there's a section of for `Options also available for subcommands` but it's only visible when viewing that command, not subcommands.  This would make it obvious from any level which options can be used.  It also makes the usage more verbose but that would be a choice for the user.

I don't need either of these features atm, no one is asking for them and I don't think they're features that will make someone decide to use the framework.  Why don't we just drop it and not clutter our issues with them.  We can revisit later if needed.
