### ISSUE TITLE
Nesting Altertnative separate classes? (CA1034 Warning)

### ISSUE THREAD

**Issue by dotnetshadow** [bilal-fazlani/commanddotnet#29]
Hi there,

I'm currently using nesting commands and was wondering if there was an alternative technique to separating classes.

I did notice that there is warning when using roslyn analysers:
https://msdn.microsoft.com/en-us/library/ms182162.aspx

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CA1034	Do not nest type Foo. Alternatively, change its accessibility so that it is not externally visible.

**Comment by bilal-fazlani** [comment]
> "Alternatively, change its accessibility so that it is not externally visible"

Right now the library is reading only public nested types. I can change it to read any nested classes including private.

**Comment by bilal-fazlani** [comment]
Added - https://github.com/bilal-fazlani/commanddotnet/commit/e7300539564f17098559120a803d8cd007c83431

**Comment by dotnetshadow** [comment]
Nice work, thanks for considering the request.

Just a thought, would you have any recommendations on structuring an application into separate classes?

**Example: Take the git example**
- git stash
- git merge

I was wondering if you could have external files such as **Stash.cs** and **Merge.cs**

**Comment by bilal-fazlani** [comment]
Hmmm, what you are asking is valid.

Let's say you have a class lying in a separate file:

```c#
public class Stash
{
    public void Pop(){}
}
```

There are two MORE ways we can implement this apart from **nested classes**

1. Attributes

```c#
public class Git
{
    [SubCommand]
    public Stash Stash {get;set;}
}
```

2. Fluent configuration

```c#
public class Git
{
    
}
```

And program.cs looks like this -

```c#
AppRunner<Git> appRunner = new AppRunner<Git>()
                                .WithSubCommand<Stash>()
                                .UseAutofac(container);

```
-------

I am thinking I am going to implement all of these. But I will begin with attribute way..
Meanwhile you can stick with nested types

**Comment by bilal-fazlani** [comment]
https://www.nuget.org/packages/CommandDotNet/1.1.10

This has the [SubCommand] Attribute. 

Do you think that [ApplicationMetadata] + [SubCommand] usage is confusing ?

**Comment by bilal-fazlani** [comment]
Readme updated : https://github.com/bilal-fazlani/CommandDotNet#nesting-commands

**Comment by dotnetshadow** [comment]
Fantastic, I'm impressed by how quickly you seem to be able to add these enhancements.

I do like the subcommand attribute.

In terms of confusion, for me I find it ok. Perhaps **ApplicationMetadata** could be named **Command**  instead, not sure if that would help things or not?

**Comment by bilal-fazlani** [comment]
Alright. I will think more about naming. 
Closing this issue now
