### ISSUE TITLE
Issues with 1.1.28 & 2.0.0

### ISSUE THREAD

**Issue by dotnetshadow** [bilal-fazlani/commanddotnet#34]
**Issue 1**
`dotnet run` is showing class name

![image](https://user-images.githubusercontent.com/296247/34858818-8bcf586a-f7a6-11e7-9540-75861c505eb4.png)

**Issue 2**
`dotnet run stxxxx` showing command garbage and showing current command name at the top

![image](https://user-images.githubusercontent.com/296247/34858879-f241425c-f7a6-11e7-9202-e7c7fdd8b144.png)

**Comment by bilal-fazlani** [comment]
Hi @dotnetshadow,
Could please share some sample code with me with which I can reproduce the garbage issue

**Comment by dotnetshadow** [comment]
@bilal-fazlani can I email?

**Comment by dotnetshadow** [comment]
**SchedulerApplication**
public class SchedulerApplication
	{        
		public SchedulerApplication()
		{            
		}
		
		public ILogger<SchedulerApplication> Logger { get; set; }

		private AppSettings Settings { get; set; }
        
		[ApplicationMetadata(Description = "All Services")]
		public void All()
		{
			Console.WriteLine(nameof(All));
		}

		[ApplicationMetadata(Description = "Service1")]
		public void Service1()
		{
			Console.WriteLine(nameof(Service1));
		}

		[ApplicationMetadata(Description = "Service2")]
		public void Service2()
		{
			Console.WriteLine(nameof(Service2));
		}
		
	    [SubCommand]
	    public InfoCommand Info { get; set; }

        [ApplicationMetadata(Description = "Service3")]
		public void Service3()
		{
			Console.WriteLine(nameof(Service3));
		}

        [SubCommand]
	    public FooCommand foo { get; set; }                
	}


**Commands/SCommand.cs**
```
 [ApplicationMetadata(Name = "FooCommand", Description = "Commnad1 Service")]
    public class FooCommand
    {
        public IFooService FooService { get; set; }

        public IEmailSender EmaillService { get; set; }

        public AppSettings Settings { get; set; }
       
        [ApplicationMetadata(Description = "Download something")]
        public async Task<bool> Download([Option]string provider = "bar")
        {

```

**Comment by bilal-fazlani** [comment]
@dotnetshadow
Unable to re-produce with your sample code

**Comment by bilal-fazlani** [comment]
This is what I tried 
```c#
using System;
using System.Threading.Tasks;
using CommandDotNet.Attributes;
using CommandDotNet.Models;

namespace CommandDotNet.Example
{
    public class SchedulerApplication
    {
        public SchedulerApplication()
        {
        }

        public ILogger<SchedulerApplication> Logger { get; set; }

        private AppSettings Settings { get; set; }

        [ApplicationMetadata(Description = "All Services")]
        public void All()
        {
            Console.WriteLine(nameof(All));
        }

        [ApplicationMetadata(Description = "Service1")]
        public void Service1()
        {
            Console.WriteLine(nameof(Service1));
        }

        [ApplicationMetadata(Description = "Service2")]
        public void Service2()
        {
            Console.WriteLine(nameof(Service2));
        }

        [SubCommand]
        public InfoCommand Info { get; set; }

        [ApplicationMetadata(Description = "Service3")]
        public void Service3()
        {
            Console.WriteLine(nameof(Service3));
        }

        [SubCommand]
        public FooCommand foo { get; set; }
    }

    [ApplicationMetadata(Name = "foo", Description = "Foo Service")]
    public class FooCommand
    {
        public IFooService FooService { get; set; }

        public IEmailSender EmaillService { get; set; }

        public AppSettings Settings { get; set; }

        [ApplicationMetadata(Description = "Download something")]
        public async Task Download([Option] string provider = "bar")
        {
        }
    }
    
    public interface ILogger<T> where T:class {}
    
    //public class Logger: ILogger<SchedulerApplication> {}
    
    public interface IFooService{}
    
    //public class FooService :IFooService {}
    
    public interface IEmailSender{}
    
    //public class EmailService : IEmailSender {}

    public class InfoCommand
    {
        public void process(){}
    }
} 
```

```c#
    class Program
    {
        static int Main(string[] args)
        {
            IServiceCollection serviceCollection = new ServiceCollection();
            
//            serviceCollection.AddSingleton<ILogger<SchedulerApplication>, Logger>();
//            serviceCollection.AddSingleton<IFooService, FooService>();
//            serviceCollection.AddSingleton<IEmailSender, EmailService>();

            IServiceProvider serviceProvider = serviceCollection.BuildServiceProvider();
            
            var appRunner = new AppRunner<SchedulerApplication>(new AppSettings
                {
                    Case = Case.LowerCase
                })
                .UseMicrosoftDependencyInjection(serviceProvider);
            
            return appRunner.Run(args);
        }
    }
```

**Comment by bilal-fazlani** [comment]
I have made a slight change in property detection. I am hoping that the issue would be resolved in https://www.nuget.org/packages/CommandDotNet/2.0.4.

If not, I need to reproduce it somehow

**Comment by bilal-fazlani** [comment]
https://www.nuget.org/packages/CommandDotNet/2.0.9 has the fixes for 

>Issue 1
>dotnet run is showing class name

**Comment by dotnetshadow** [comment]
Thanks, I'll give it a go today. Is there a way to send you code privately if it doesn't work?

**Comment by bilal-fazlani** [comment]
Yes please send it via email, on bilal.m.fazlani@gmail.com

**Comment by dotnetshadow** [comment]
I've just sent you some code via email, hope it helps

**Comment by bilal-fazlani** [comment]
@dotnetshadow 
I have emailed you back a sample project. Please run it as it without any modifications and let me know what you see. For me, it doesn't show garbage data. I am suspecting it might be related to OS. I am running on mac os.

**Comment by bilal-fazlani** [comment]
Also, I just came across this: https://stackoverflow.com/questions/6513648/how-do-i-filter-out-c-displayclass-types-when-going-through-types-via-reflecti

I can implement it everywhere but being able to reproduce it would have been awesome

**Comment by bilal-fazlani** [comment]
<img width="656" alt="screen shot 2018-01-13 at 2 04 30 pm" src="https://user-images.githubusercontent.com/3396271/34904382-b24db922-f86a-11e7-8125-136a21bfedfa.png">

Apparently IT IS a runtime specific issue. I will use a windows to fix this problem.

**Comment by bilal-fazlani** [comment]
I made a few changes and made a few thing explicit. This had to be done to bring some consistency considering the differences between mono & clr.

1. Every dependency property now needs a [InjectProperty] attribute
2. Nested types need [SubCommand] attribute.

Readme file updated. Closing the issue.

**Comment by dotnetshadow** [comment]
I'm currently testing 2.0.12 but I can't seem to reference the **InjectProperty**, any ideas?

**Comment by bilal-fazlani** [comment]
Thank you for bringing these issues up! & thanks for your patience!
