### ISSUE TITLE
UseVersionMiddleware not work when publish to .exe single file

### ISSUE THREAD

**Issue by kashti3** [bilal-fazlani/commanddotnet#418]
Hi, 

I added the UseVersionMiddleware ability to my CLI project and when I testing it on a non publish ouput .exe file in seem to be work but will trying to test it after publish into a single file I get this result:

C:\CLI>[CliExeFileName] -v
[CliExeFileName].exe
The path is empty. (Parameter 'path')

**Comment by drewburlingame** [comment]
Thanks kashti3.  Free time is hard to come by atm but I'll find some time to look into this over this during the week.

**Comment by drewburlingame** [comment]
Thankfully, MiloszKrajewski figured this out already for Spectre Console.  https://github.com/spectreconsole/spectre.console/issues/242.  I'll get an update pushed in the next couple of days.

Thank you @MiloszKrajewski

**Comment by drewburlingame** [comment]
this has been fixed and released in https://www.nuget.org/packages/CommandDotNet/6.0.3
