### ISSUE TITLE
When Using .UseDefaultMiddleware(excludeVersionMiddleware : true) on a single file output received "Unrecognized command or argument '-v'" error

### ISSUE THREAD

**Issue by kashti3** [bilal-fazlani/commanddotnet#419]
While using...
....
AppRunner<MainCliModel>(settings)
        .UseDefaultMiddleware(excludeCancellationHandlers : true,
                              excludeVersionMiddleware : true).Run(args);
.....

When trying to run [exeFileName] -v receiving "Unrecognized command or argument '-v'" error message

**Comment by drewburlingame** [comment]
This is by design. The version option is only added to the root command when the version middleware is used.
