### ISSUE TITLE
Call commands from other commands

### ISSUE THREAD

**Issue by dotnetshadow** [bilal-fazlani/commanddotnet#42]
Great effort with this library, I like the new features you have been implementing

I was wondering how you would go about handling or structuring the following requirement

Say I have 3 commands
**Command1**, **Command2** and **All**

For my All Command I would like to call **Command1** and **Command2**
Currently I'm able to do this by doing the following:

```
[DefaultMethod]
public void AllCommand() {
   var command1 = new Command1();
   command1.DoSomethng();
}
```

While this works, the issue is if **Command1** has dependencies IFooService this wouldn't be injected because I'm newing up commmands. 

I'm just wondering how you would about structuring such a requirement?

Thanks for your time and effort

**Comment by dotnetshadow** [comment]
I realised that when I do new Command1() I can set the properties for my injected services

```
[InjectProperty]
public IFooService FooService { get; set; }

var command1 = new Command1 {
     FooService  = FooService 
}
```

The AllCommand would then need every service that would be required by whatever commands it needs to use. I'm thinking there must be a cleaner way for this?

**Comment by bilal-fazlani** [comment]
This seems a very specific requirement. It's best if you implement it. Or suggest a way it can be done in a generic way.

**Comment by dotnetshadow** [comment]
@bilal-fazlani Yes I was thinking it could be a specific requirement, I didn't know if there was some support for this already. 

If I was to think in generic temrs, I would have to mark my Commands as ICommand and then I would be able to call my commands through injection, just thinking out loud.

But you are correct perhaps not needed as a generic solution

**Comment by drewburlingame** [comment]
Could your All command have a dependency on Command1 and Command2?  the DI framework would inject all requirements into those services

**Comment by dotnetshadow** [comment]
@drewburlingame I just saw this comment now, yes I would like to achieve that. Have the ability for a command to depends on another command. 

How would you go about letting DI inject these requirements? Could you provide some sample code?

**Comment by drewburlingame** [comment]
@dotnetshadow  since you were able to solve this with DI, do you mind if we close this PR?

**Comment by dotnetshadow** [comment]
@drewburlingame we can close this. 

Guess i was wondering if the way i solved it was a good way or not

**Comment by drewburlingame** [comment]
Yes, it's the best way to solve it.
