### ISSUE TITLE
Change usage for root app

### ISSUE THREAD

**Issue by PetterT2** [bilal-fazlani/commanddotnet#43]
Hi,

We are running .Net core, and global tools, so we would like to have the option to specify the "Usage:" help text.
Today it's hard coded in AppCreator.cs as: $"dotnet {Assembly.GetEntryAssembly().GetName().Name}.dll";
Would appreciate an option to override this, as the usage is not correct in regards to using global tools.

Best regards

**Comment by bilal-fazlani** [comment]
It'a valid request. I will have this added soon

**Comment by bilal-fazlani** [comment]
Updated version https://www.nuget.org/packages/CommandDotNet/2.6.0

You can now use the `Name` property in `[ApplicationMetadata]` attribute on the root level and it will shown in the "Usage" in help text. Earlier this `Name` property was ignore on root command level.
