### ISSUE TITLE
Blocking creating a commanddotnet.ioc.simpleinjector

### ISSUE THREAD

**Issue by drewburlingame** [bilal-fazlani/commanddotnet#44]
The ms & autofac ioc extensions reference the internal field AppRunner.DependencyResolver  which in turn requires an "[assembly: InternalsVisibleTo("CommandDotNet.IoC.MicrosoftDependencyInjection")]" line.   This prevents us from implementation a new ioc tech w/o first getting a PR merged into your master.  If enough people adopt this, that class will be littered.    Can DependencyResolver be converted to a property with an external setter and a private or internal getter?

**Comment by bilal-fazlani** [comment]
Now you can do this:

```c#
AppRunner<App> appRunner = new AppRunner<App>()
                .UseDependencyResolver(new CustomDependencyResolver());
```

`CustomDependencyResolver` is a class created by you which implements `IDependencyResolver`

Check it out!

**Comment by bilal-fazlani** [comment]
[Nuget package version 2.6.5](https://www.nuget.org/packages/CommandDotNet/2.6.5) has this feature available
