### ISSUE TITLE
Generic Host in 2.1

### ISSUE THREAD

**Issue by dotnetshadow** [bilal-fazlani/commanddotnet#46]
Hi there,

Just wondering if you had thoughts on trying to use the generic host introduced in 2.1 as a way to push through dependencies / logging etc 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1

**Comment by bilal-fazlani** [comment]
I am not sure if it aligns with this project. Do you think it does? if yes, how do you think it can be leveraged and what advantages would it provide over current implementation?

**Comment by dotnetshadow** [comment]
After looking into this further, maybe not. 

I guess I was thinking it would of been a good way to use dependency injection and handling cost cutting concerns in console apps. But as you said I think it might not be part of this project and might be able to be used in combination with your library

**Comment by bilal-fazlani** [comment]
Yes, that makes sense
