### ISSUE TITLE
Bug report: Line 36 of CommandDotNet.AppConfigBuilder

### ISSUE THREAD

**Issue by RobinsonMW** [bilal-fazlani/commanddotnet#464]
While going through your "CancelMe" example I think I've identified a bug.  When I made the change below the example worked correctly.

Thanks.

Line 36 of CommandDotNet.AppConfigBuilder should read:

[typeof(IEnvironment)] = ctx => ctx.Environment,
not 
[typeof(IEnvironment)] = ctx => ctx.Console,

**Comment by drewburlingame** [comment]
Thanks for taking the time to file this.  You're correct, that's a bug.  I've pushed a fix and will generate a new package tomorrow.

**Comment by drewburlingame** [comment]
package has been published with the updates. https://www.nuget.org/packages/CommandDotNet
