### ISSUE TITLE
Minor typo in doc

### ISSUE THREAD

**Issue by AldeRoberge** [bilal-fazlani/commanddotnet#485]
![image](https://user-images.githubusercontent.com/4276275/233891919-bf146645-514a-4e36-a0d5-ae8db3bc7f84.png)

https://commanddotnet.bilal-fazlani.com/gettingstarted/getting-started-140-default-commands/#command-per-class-pattern

I wanted to change myself, but couldn't find a link to the doc's repo.

Cheers for this awesome library!

**Comment by AldeRoberge** [comment]
Found another minor typo

![image](https://user-images.githubusercontent.com/4276275/233892144-a955c9a3-e0dc-4119-ad73-9ef25784253a.png)

https://commanddotnet.bilal-fazlani.com/gettingstarted/getting-started-500-interceptors/#interceptors

**Comment by drewburlingame** [comment]
Thanks for pointing these out.  The docs are in this repo... https://github.com/bilal-fazlani/commanddotnet/tree/master/docs and we welcome your contributions.

**Comment by drewburlingame** [comment]
these have been resolved.  thanks for posting.
