### ISSUE TITLE
Dispose is called before async command finishes executing

### ISSUE THREAD

**Issue by Sibusten** [bilal-fazlani/commanddotnet#488]
The implementation of `AppRunner.OnRunCompleted` does not await `next`, causing the event to be fired before the async command finishes executing. This causes `Dispose` to be invoked early.

```cs
private Task<int> OnRunCompleted(CommandContext context, ExecutionDelegate next)
{
    var result = next(context);
    context.AppConfig.OnRunCompleted?.Invoke(new OnRunCompletedEventArgs(context));
    return result;
}
```

**Comment by drewburlingame** [comment]
Thanks for filing this @Sibusten.  I'll look into it this week.  If you need this immediately, I'll happily accept a PR with tests.

**Comment by drewburlingame** [comment]
this is resolved with https://www.nuget.org/packages/CommandDotNet/7.0.3.  Thanks for reporting and helping with the tests.
