### ISSUE TITLE
Model support - composing objects to reuse common arguments

### ISSUE THREAD

**Issue by drewburlingame** [bilal-fazlani/commanddotnet#49]
In cases where you want ubiquitous arguments (--dryrun, --verbose, --fail-fast, --customer) it would be great to define those only once so we don't have to redefine them for each command.  I didn't see a way to do this.  

If there isn't a way to do it, I was thinking that with the Model support you've added, if a property of the IArgumentModel class was also of type IArgumentModel, then the framework could create an instance and map those arguments as well.  

What do you think?

**Comment by bilal-fazlani** [comment]
I think the use case is valid. I can do it when I get some free time (which I rarely get these days) or I can also accept a PR with unit tests

**Comment by drewburlingame** [comment]
Great.  We're working on it now.  Would you like us to add an example to the demo and/or document in the readme?
