### ISSUE TITLE
simply remove dependency 'Microsoft.CSharp v4.7.0'

### ISSUE THREAD

**Issue by mur-dock** [bilal-fazlani/commanddotnet#493]
Starting with .net5+ there is no need to add this reference to your project.
It seems that this is a remnant of the migration from .netstandard2.0 to .net5.0. (CommandDotNet v5.0.0).

**Comment by drewburlingame** [comment]
resolved in https://www.nuget.org/packages/CommandDotNet/7.0.4.  Thanks for posting.
