### ISSUE TITLE
Type 'Decimal' is not supported'

### ISSUE THREAD

**Issue by al322se** [bilal-fazlani/commanddotnet#53]
Just leave this issue here. It was unexpectedly for me that library doesn't support decimal(as type of property in the model). So I hope someone who faced the similar issue can find this issue

**Comment by drewburlingame** [comment]
can this issue be close now?  https://github.com/bilal-fazlani/commanddotnet/blob/master/CommandDotNet/Models/ArgumentInfo.cs#L143

**Comment by drewburlingame** [comment]
looks like the [readme](https://github.com/bilal-fazlani/commanddotnet#supported-parameter-types) needs to be updated

**Comment by drewburlingame** [comment]
I also realized decimal isn't supported everywhere.  I'm working on a PR for this and to prevent implementing partial support for a type.

**Comment by drewburlingame** [comment]
closed by #78
