### ISSUE TITLE
Feature request: Place parameters in the middle.

### ISSUE THREAD

**Issue by SebastianStehle** [bilal-fazlani/commanddotnet#58]
Hi,
I am not sure if it makes sense, but very often I have commands like

    cli gateway get-configuration 1A827Ah66
    cli gateway add-x 1A827Ah66

The `1A827Ah66` is an id or longer name and when I have to use multiple commands it is annoying to reenter it all the time. Therefore it would be more convenient to have the following syntax:

    cli gateway 1A827Ah66 get-configuration 
    cli gateway 1A827Ah66 add-x 

So that I only have to replace the last part. Is it somehow possible?

**Comment by bilal-fazlani** [comment]
Is there an example of this feature in any popular cli tool?
This seems pretty unusual syntax. 

You can do it like this

```bash
cli gateway -b 1A827Ah66 get-configuration 
cli gateway -b 1A827Ah66 add-x
```

**Comment by SebastianStehle** [comment]
Okay, good idea.
