### ISSUE TITLE
Arguments do not generate their help texts accordingly.

### ISSUE THREAD

**Issue by taori** [bilal-fazlani/commanddotnet#63]
![grafik](https://user-images.githubusercontent.com/5545184/50624723-3f31a180-0f23-11e9-9d8a-6e65be01423d.png)

**Comment by bilal-fazlani** [comment]
It can be re produced. 

<img width="1013" alt="screenshot 2019-01-04 at 9 37 45 pm" src="https://user-images.githubusercontent.com/3396271/50697697-fd127800-1068-11e9-9ca6-202b5228f689.png">

**Comment by bilal-fazlani** [comment]
I have fixed this issue. Looks like there are some missing tests. I need to add tests to test the rendering logic of help

**Comment by taori** [comment]
Cool thing. thanks
