### ISSUE TITLE
Support for sourcelink

### ISSUE THREAD

**Issue by taori** [bilal-fazlani/commanddotnet#64]
Adding sourcelink to the project would greatly benefit the project, because anyone could easily debug it and figure out what exactly is going wrong. Just now i'm having a bug, which would be easily detectable with this :)

I will provide help if you want.

**Comment by bilal-fazlani** [comment]
I had to disable it last time due to some issues. https://github.com/NuGet/Home/issues/6082
Will enable again for next release

**Comment by bilal-fazlani** [comment]
I am hoping this should do it. https://github.com/bilal-fazlani/commanddotnet/commit/16e5d3a0fd81f0ac4254d4da4d8c53260d3ff858

**Comment by taori** [comment]
@bilal-fazlani any specific reason you change netcore to 2.2 on the main project? That would limit its usage.

Also you might need to verify whether stepping into code works. appveyor does not support snupkg yet and debugging for snupkg doesnt seem to be working properly yet. That's why i went for DebugType=embedded + EmbedAllSources. That way sourcelink never did any file loading and worked out of the box

**Comment by bilal-fazlani** [comment]
> any specific reason you change netcore to 2.2 on the main project? That would limit its usage.
We are back to 2.1 now

> appveyor does not support snupkg yet and debugging for snupkg doesnt seem to be working properly yet. That's why i went for DebugType=embedded + EmbedAllSources. That way sourcelink never did any file loading and worked out of the box

Ok we are back to symbols.nupkg format. 

This is how csproj looks like now

```
<PublishRepositoryUrl>true</PublishRepositoryUrl>
<IncludeSymbols>true</IncludeSymbols>
<EmbedAllSources>true</EmbedAllSources>
<DebugType>embedded</DebugType>
<DebugSymbols>true</DebugSymbols>
```
https://ci.appveyor.com/project/bilal-fazlani/commanddotnet/build/artifacts

>Also you might need to verify whether stepping into code works.

I will do that

**Comment by bilal-fazlani** [comment]
Question @taori , with this, do I still need to publish a symbols package?

**Comment by bilal-fazlani** [comment]
Awesome.
