### ISSUE TITLE
NullReferenceException when executed in MSTest

### ISSUE THREAD

**Issue by erdmenchen** [bilal-fazlani/commanddotnet#65]
I have the following simple console application:
```
    public class Program
    {
        public static int Main(string[] args)
        {
            var app = new AppRunner<DummyApp>();

            return app.Run(args);
        }
    }
```
When executing `Main` inside a MSTest UnitTest, I get a NullReferenceException:
```
    [TestClass]
    public class ProgramTest
    {
        [TestMethod]
        public void RunTest()
        {
            var result = Program.Main(new[] { "-h" });

             Assert.AreEqual(0, result);
        }
    }
```

Exception Details:
> System.NullReferenceException
>   HResult=0x80004003
>   Message=Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>   Source=CommandDotNet
>   StackTrace:
>    at CommandDotNet.AppCreator.CreateApplication(Type type, IDependencyResolver dependencyResolver, CommandLineApplication parentApplication)
>    at CommandDotNet.AppRunner`1.Run(String[] args)
>    at Program.Main(String[] args) in [...]\Program.cs:line 11
>    at ProgramTest.RunTest() in [...]\ProgramTest.cs:line 11
> 

How can I initialize the `AppRunner` for the UnitTest context? To me it seems like the `DependencyResolver` and/or the `CommandLineApplication` are not set...

**Comment by bilal-fazlani** [comment]
Could you please show the code for `DummyApp` ?

**Comment by erdmenchen** [comment]
Just a plain empty app:

```    
public class DummyApp
    {
        public void Run()
        {
            System.Console.WriteLine("Running...");
        }
    }
```

**Comment by bilal-fazlani** [comment]
I am trying to reproduce this. 

```c#
public class Program
{
    public static int Main(string[] args)
    {
        var app = new AppRunner<DummyApp>();
        return app.Run(args);
    }
}
public class DummyApp
{
    public void Run()
    {
        System.Console.WriteLine("Running...");
    }
}
```

Test:

```c#
[TestClass]
public class ProgramTest
{
    [TestMethod]
    public void RunTest()
    {
        var result = Program.Main(new[] { "-h" });
        Assert.AreEqual(0, result);
    }
}
```

It works as expected on my machine. 

<img width="1236" alt="screenshot 2019-02-10 at 7 46 46 pm" src="https://user-images.githubusercontent.com/3396271/52534853-aafdfa00-2d6c-11e9-83db-1a5f27d4cdbb.png">

@erdmenchen

**Comment by bilal-fazlani** [comment]
> How can I initialize the `AppRunner` for the UnitTest context? To me it seems like the `DependencyResolver` and/or the `CommandLineApplication` are not set...

We don't really have to do anything to initialize AppRunner in UnitTest context. AppRunner isn't aware that its running in a unit test of externally. So that should not matter...

**Comment by erdmenchen** [comment]
Ok thank you very much for the fast response.

One small detail, that maybe is necessary to point out:
I am running a standard .net framework 4.6.1 project, not a .net core project.

And the unit test project is a .net framework 4.6.1 project, too.

Does this make a difference?

**Comment by bilal-fazlani** [comment]
> Does this make a difference?

It might. I have a mac so it's not possible for me to reproduce it on my local machine. Let me try to reproduce this on appveyor.

**Comment by bilal-fazlani** [comment]
btw, @erdmenchen  which version of CommandDotNet are you using?

**Comment by erdmenchen** [comment]
I´m sorry: I am using the latest stable version 2.7.5.

**Comment by erdmenchen** [comment]
I cannot switch to the latest version (2.7.12-beta) because you switched from .netstandard 2.0 to .netcoreapp 2.1.

**Comment by bilal-fazlani** [comment]
Thank you for bringing this up. This change was not intentional. I am looking into it.

**Comment by erdmenchen** [comment]
I think I found the issue:

In AppCreator you are using `Assembly.GetEntryAssembly()` which returns `null` when executed in a .net UnitTest project:
https://github.com/bilal-fazlani/commanddotnet/blob/7967d9e150baab292b685891e9d6165b1a677bc9/CommandDotNet/AppCreator.cs#L36

Also in AppCreator:
https://github.com/bilal-fazlani/commanddotnet/blob/7967d9e150baab292b685891e9d6165b1a677bc9/CommandDotNet/AppCreator.cs#L72

Changing both calls to `Assembly.GetExecutingAssembly()` resolves the issue.

**Comment by erdmenchen** [comment]
@bilal-fazlani what is your opinion about this? 
Are you considering to fix this?

**Comment by bilal-fazlani** [comment]
@erdmenchen 
If I simply replace `Assembly.GetEntryAssembly()` with `Assembly.GetExecutingAssembly()`, I don't get expected values for `assemblyName` and `ProductVersion`. 

Instead of returning actual end user assembly name & version, it returns me the assembly name & version of `CommandDotNet`

**Comment by bilal-fazlani** [comment]
<img width="1067" alt="Screenshot 2019-04-02 at 9 58 17 PM" src="https://user-images.githubusercontent.com/3396271/55419632-caf2b280-5592-11e9-81f8-d7087292e47d.png">

**Comment by bilal-fazlani** [comment]
I just tried to reproduce this error on my mac using the following code:

```c#
namespace TestProject1
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var program = new Program();
            var result = program.Main(new[] { "-h" });
            Assert.AreEqual(0, result);
        }
    }
    
    public class Program
    {
        public int Main(string[] args)
        {
            var app = new AppRunner<DummyApp>();

            return app.Run(args);
        }
    }
    
    public class DummyApp
    {
        public void Run()
        {
            System.Console.WriteLine("Running...");
        }
    }
}
```

Here it seems to be working fine: 

<img width="1185" alt="Screenshot 2019-04-02 at 10 08 40 PM" src="https://user-images.githubusercontent.com/3396271/55420139-f1fdb400-5593-11e9-9f75-caf21da8c004.png">

**Comment by bilal-fazlani** [comment]
I think this is behaving differently because of differences in full dotnet framework and dotnet core. At this point, I don't really have a solution to this problem.

**Comment by drewburlingame** [comment]
This [SS post](https://stackoverflow.com/questions/14165785/i-need-an-alternative-to-assembly-getentryassembly-that-never-returns-null) has a link explaining the problem and a solution at the bottom that could work.  Alternatively, a Func<Assembly> method could be added to AppSettings or registered with AppRunner.WithConsoleAssembly.  Or use GetEntryAssembly or MainModule as the default and allow override via AppSettings or AppRunner.

**Comment by bilal-fazlani** [comment]
Or I could probably do something like:

```c#
#if NETFULL
    Console.WriteLine("NETFULL");
#else
    Console.WriteLine("NETCORE");
#endif
```

source: https://weblog.west-wind.com/posts/2017/jun/22/multitargeting-and-porting-a-net-library-to-net-core-20#Framework-Specific-Differences

**Comment by erdmenchen** [comment]
Please, please add this to the project in order to fix  the current bug, so that we are able to write high level unit tests.

Thank you so much!

**Comment by drewburlingame** [comment]
@erdmenchen if you have the version command enabled in your app, you'll need to disable it for the tests.

**Comment by erdmenchen** [comment]
Thank you very much for this quick fix. 
I just tested the new version 2.7.14-beta and was able to run unit tests that directly call e.g.
`Program.Main(new[] { "-h" });`

However there seems to be a new bug introduced with this approach, I opened a new ticket:
https://github.com/bilal-fazlani/commanddotnet/issues/74
