### ISSUE TITLE
start commands from readline (interactive)

### ISSUE THREAD

**Issue by vip32** [bilal-fazlani/commanddotnet#69]
what are the possibilities to build an interactive console application with commanddotnet? instead of arguments provided with app startup, the same arguments can be given by using a readline. when the readline is ready there should be some way to start a command (CommandRunner.RunCommand?).

can something like this be done with commanddotnet?

**Comment by bilal-fazlani** [comment]
Its not possible right now. But it seems that this should not be complicated to achieve.

**Comment by drewburlingame** [comment]
Is it possible to create a new instance of AppRunner within command like the following?   I haven't tested this.   If this does work, I was wondering as a next step if Echo could be extracted into another class that CliApplication inhertis so the inner AppRunner can use the base class without including the Cli command.

``` c#

    [ApplicationMetadata(Name = "cli", Description = "Sample interactive console")]
    public class CliApplication 
    {
        [InjectProperty]
        public AppSettings AppSettings { get; set; }
        
        [ApplicationMetadata(Description = "Enter interactive mode")]
        public void Cli()
        {
            Console.Out.WriteLine("Interactive mode");
            while (true)
            {
                //TODO: do not split quoted spaces
                var input = Console.ReadLine().Split(new[] {' '}, StringSplitOptions.RemoveEmptyEntries);
                if (input.Length == 1 && (input[0] == "exit" || input[0] == "quit"))
                {
                    break;
                }

                AppRunner<CliApp2> appRunner = new AppRunner<CliApp2>(AppSettings);
                appRunner.Run(input);
            }
        }

        [ApplicationMetadata(Description = "Echo console")]
        public void Echo(string input)
        {
            Console.Out.WriteLine(input);
        }
    }
```

**Comment by vip32** [comment]
got something working by using another lib
https://github.com/commandlineparser/commandline
