### ISSUE TITLE
Command usage is not printed right in v2.7.14-beta

### ISSUE THREAD

**Issue by erdmenchen** [bilal-fazlani/commanddotnet#74]
While testing the current release 2.7.14-beta the following bug shows up related to the fix of this ticket: https://github.com/bilal-fazlani/commanddotnet/issues/65

Before this fix, the help text for a command showed:
`Usage: ApplicationName.exe commandName [arguments] [options]`

Now it shows
`Usage: commandName ApplicationName.exe [arguments] [options]`

Before this fix it showed this for sub commands:
`Usage: ApplicationName.exe commandName [options] [command]`

Now it shows
`Usage: commandName ApplicationName.exe [options] [command]`

So it appears to me, that somehow the order of the app name and command name is reversed?
I tested this for .NET 4.6.1. Before I was using version 2.7.5 of commanddotnet.

EDIT:
Also it showed this for 2nd lvl subcommands befor:
`Usage: ApplicationName.exe commandName1 commandName2 [arguments] [options]`

And now it shows:
`Usage: commandName2 commandName1 ApplicationName.exe [arguments] [options]`
So the order of the subcommands is also wrong.

**Comment by drewburlingame** [comment]
thanks for the filing this.  I'll look into it tomorrow and add some tests.

**Comment by erdmenchen** [comment]
Thank you very much, will test again, when a new release is published.

**Comment by erdmenchen** [comment]
@bilal-fazlani when will you release this?

**Comment by bilal-fazlani** [comment]
@drewburlingame if this is fixed, you can may be push a new tag "2.7.15-beta" and it will trigger the release pipeline.

**Comment by erdmenchen** [comment]
I can confirm, that it is fixed for version 2.7.15-beta 👍
